module.exports = {
  kod: "şaka",
  async run (client, message, args) {
    const Discord = require('discord.js')
    var Şakalar = [
      'Tuvaletteki 10’a ne denir? -SİFON',
      'En güzel yemek yapan Ceren hangisidir? -TENCEREN',
      'İshal olmuş böceğe ne denir? -CIRCIR BÖCEĞİ',
      'Bacaktaki 10’a ne denir? -PANTOLON',
      'Türkiye’nin en yeni şehri hangisidir? -NEVŞEHİR',
      'Yıkanan ton balığına ne denir? -WASHINGTON',
      'Baykuşlar vedalaşırken ne der? -BAY BAY BAYKUŞ',
      'Yemeğin suyuna kim bandı? -KOLİ BANDI',
      'Bebeğe patik giydirmeye çalışmışlar ama giymemiş neden? -BEBEK ANTİPATİKMİŞ',
      'İngilizler kendi kıllarına ne der? -MICHEAL',
      'Gülen ördeğe ne denir? -KIKIR-DUCK',
      'Örümcek adam ağ atamıyormuş neden? -ÇÜNKÜ AĞ BAĞLANTISI KOPMUŞ',
      'Siviller hangi dili konuşur? -SİVİLCE',
      'En değerli meşe hangisidir? -İZZET ALTINMEŞE',
      'Küçük su birikintisine ne denir? -SUCUK',
      'Hiç bozuk paran var mı? -YOK ÇÜNKÜ HEPSİNİ TAMİR ETTİRDİM',
      'Taşımasu annesinden nasıl su ister? -MATARAMASUKO',
      'Aya ilk bayrağı kim dikmiştir? -TERZİ',
      'İneklerin sevmediği element? -AZ-OT',
      'Kırmızı giyen erkeğe ne denir? -ALBAY',
      'En çok eşek yavrusu nerde bulunur? -SPA MERKEZİNDE',
      'Pişmemiş burgere ne denir? -HAMBURGER',
      'Dört tarafı suyla çevrili çaya ne denir? -ADAÇAYI',
      'Son gülen en geç anlayandır.',
      'İnsanların seni ezmesine izin verme. Ehliyet al, sen onları ez...',
      'İlahi Azrail ... Sen adamı öldürürsün!',
      'Ben mafya babasıyım çünkü oğlumun adı Mafya.',
      'Kim vurduya gittim birazdan geleceğim.',
      'Zenginler et, fakirler hayalet yer.',
      'Hava korsanı uçağı kaçıracaktı ama yapamadı çünkü uçağı kaçırdı.',
      'Canın sıkıldıysa gevşet.',
      'Almanya’da Almanlar, Sakarya’da sakarlar yaşar.',
      'Sana bir kıllık yapayım, kıllarını koyarsın.',
      'Seven unutmaz oğlum, eight unutur.',
      'Cem Uzan, üstünü örteyim.',
      'Haydi Unkapanı’na gidip birkaç kapan kuralım. Belki un yakalarız',
      'Adamın biri güneşte yanmış, ay da düz.',
      'Sinemada on dakika ara dedi, aradım aradım açmadı.',
      'Röntgen Filmi çektirdik, yakında sinemalarda.',
      'Geçen gün taksi çevirdim hala dönüyor.',
      'Ben hikâye yazarım Ebru Destan.',
      'Geçen gün geçmiş günlerimi aradım ama meşguldü.',
      'Tebrikler kazandınız, şimdi tencere oldunuz!',
      'Kaba kuvvet uygulama, kap kırılabilir.',
      'Ayna’nın karşısında süslenme, Manganın karşısında süslen.',
      'Geçen file çorap aldım, zürafaya almadım.',
      'Yılanlardan korkma, yılmayanlardan kork.',
      'Ben kahve içiyorum, Nurgül Yeşilçay.',
      'Bak şu karşıdaki uçak PİSTİ, ama bir türlü temizlemediler.',
      'Geçen gün geçmiş günlerimi aradım ama meşguldü.',
      'Adamın birisi televizyona çıkmış bir daha indirememişler.',
      'Adamın biri gülmüş, saksıya koymuşlar.',
      'Funda Arar dediler ama hala daha aramadı.',
      'Adamın kafası atmış bacakları eşek.',
      'Uzun lafın kısası: U.L.',
      'Yağmur yağmış, kar peynir!',
      'Sakla samanı, inekler aç kalsın.',
      'Baraj dendi mi, akan sular durur.',
      'Dünya dönermiş ay da köfte…',
      'Son gülen en geç anlayandır.',
      'Bu erikson, başka erik yok.',
      'Sen kamyonu al, Leonardo da vinci.',
      'Adamın biri gülmüş, bahçeye dikmişler.',
      'Top ağlarda, ben ağlamaz mıyım?',
      'Ben yürüyelim diyorum Gerard Depardieu.',
      'Ahmet Saz çaldı. Polis tutukladı.',
      'Beni ayda bir sinemaya götürme, Marsta bir sinemaya götür.',
      'Ben ekmek yedim Will Smith.',
      'Aaaaa siz çok terlemişsiniz durun size terlik getiriyim.',
      'Kalbinin sesini dinle güzelse kaset yap',
      'Bağırsaklarda yaşayan tenya kurtları bağırsakta yaşarlar bağırmasak da yaşar.',
      'Çiçeğin biri solmuş diğeri de sağ.',
      'Lütfen sessiz olun telefon faturasını yeni yatırdım uyuyor şimdi uyanmasın',
      'Nuri ölünce Çine gömsünler, nur içinde yatsın.',
      'İngilizcem yok, tanıdığım bütün Cemler Türk.',
      'Sarımsağı havanda dövmüşsün, Ha Muşta.',
      'Dondurmayı ben yalamam, himalayalar.',
      'Yarasa yararlı bir hayvandır. Yararlı bir hayvan olmasaydı yaramasa derlerdi.',
      'Kelebekler, köstebekler ama ben beklemem.',
      'Bütün umutlarım suya düştü ama boğulmadılar. Çünkü onlara yüzme öğretmiştim',
      'Bu gece seni kınıyorum, çünkü kına gecesi.',
      'Basamakta durmayın otomatik kapı çarpar, böler, karekökünü alır.',
      'Hayırlı olsun Araba almışsın. Evet aldık. Niye Araba aldın ki kendine alsaydın.',
      'Çok Makbule geçti, şimdi de Fatma geçiyor.',
      'Adamın kafası atmış bacakları eşek.',
      'Geçen gün geçmiş günlerimi aradım ama meşguldü.',
      'Sinüs 60, kosinüs tutmuş…',
      'Yağmur yağmış, kar peynir!',
      'Baraj dendi mi, akan sular durur.',
      'Kediler niçin havaalanına gidemez? Çünkü pist var.'
    ];
    var şaka = Math.floor(Math.random()*Şakalar.length);
    const embed  = new Discord.MessageEmbed()
    .setThumbnail('https://media.giphy.com/media/8luTfdpQhNxwJ6l8xv/giphy.gif')
    .setColor("RANDOM")
    .addField('Gül gül ölürsün', `${Şakalar[şaka]}`);
    message.channel.send(embed)
  }
}
